//login
export const POST_LOGIN_REQUEST = "POST_LOGIN_REQUEST";
export const POST_LOGIN_REQUEST_SUCCESS = "POST_LOGIN_REQUEST_SUCCESS";
export const POST_LOGIN_REQUEST_FAIL = "POST_LOGIN_REQUEST_FAIL";

//add user
export const ADD_USERS_REQUEST = "ADD_USERS_REQUEST";
export const ADD_USERS_REQUEST_SUCCESS = "ADD_USERS_REQUEST_SUCCESS";
export const ADD_USERS_REQUEST_FAIL = "ADD_USERS_REQUEST_FAIL";

//logout
export const USER_LOGOUT = 'USER_LOGOUT';
